apiVersion: apps/v1
kind: Deployment
metadata: {name: checkout-api}
spec:
  replicas: 3
  selector: {matchLabels: {app: checkout-api}}
  template:
    metadata: {labels: {app: checkout-api}}
    spec:
      containers:
        - name: checkout-api
          image: checkout-api:v1.9.0
          resources:
            requests: {memory: 256Mi, cpu: 100m}
            limits: {memory: 1Gi, cpu: 500m}
