"""LLM abstraction with deterministic fallback for credential-free demos."""
from .config import settings

SYSTEM_PROMPT = """You are AIOps Guardian Pro. Produce concise, evidence-backed operational analysis.
Never invent evidence. Never bypass guardrails. Explicitly state uncertainty when evidence is insufficient.
Operational mutations are recommendations until deterministic platform policy permits execution."""

class LLMService:
    def available(self): return bool(settings.openai_api_key)
    def summarize(self, evidence, question):
        if not self.available():
            return "Demo mode: deterministic RCA is generated by the domain agents."
        from langchain_openai import ChatOpenAI
        from langchain_core.messages import HumanMessage, SystemMessage
        llm=ChatOpenAI(model=settings.openai_model,api_key=settings.openai_api_key,temperature=0)
        msg=f"Question: {question}\nEvidence: {evidence}\nReturn an evidence-backed operational summary."
        return llm.invoke([SystemMessage(content=SYSTEM_PROMPT),HumanMessage(content=msg)]).content

llm_service=LLMService()
